"""
KV Burhanpur — Teacher Arrangement / Substitution App
Run: python3 -m streamlit run app.py --browser.gatherUsageStats=false
"""

import datetime, os, hashlib
import pandas as pd
import streamlit as st

MASTER_CSV    = "timetable_master.csv"
LOG_CSV       = "arrangements_log.csv"
DAYS_ORDER    = ["MON", "TUE", "WED", "THU", "FRI", "SAT"]
DAY_MAP       = {0:"MON",1:"TUE",2:"WED",3:"THU",4:"FRI",5:"SAT",6:"MON"}
ALL_PERIODS   = list(range(1, 9))
AVATAR_COLORS = ["#4F46E5","#0891B2","#059669","#D97706","#DC2626",
                 "#7C3AED","#DB2777","#0284C7","#65A30D","#9333EA","#EA580C","#0F766E"]

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def av_color(name: str) -> str:
    return AVATAR_COLORS[int(hashlib.md5(name.encode()).hexdigest(), 16) % len(AVATAR_COLORS)]

def av_initials(name: str) -> str:
    s = name.upper()
    for p in ["MR. ","MS. ","MRS. ","DR. "]:
        s = s.replace(p, "")
    parts = s.strip().split()
    return (parts[0][0] + (parts[1][0] if len(parts) > 1 else "")).upper()

def short_name(name: str) -> str:
    for p in ["MR. ","MS. ","MRS. ","DR. "]:
        if name.upper().startswith(p):
            return name[len(p):].strip()
    return name.strip()

@st.cache_data
def load_master() -> pd.DataFrame:
    df = pd.read_csv(MASTER_CSV)
    df["Teacher_Name"] = df["Teacher_Name"].str.strip()
    df["Class"]        = df["Class"].fillna("").str.strip()
    df["Subject"]      = df["Subject"].fillna("").str.strip()
    return df

def get_schedule(df, teacher, day):
    return df[(df["Teacher_Name"]==teacher) & (df["Day"]==day)].sort_values("Period").reset_index(drop=True)

def busy_set(df, day, period) -> set:
    return set(df[(df["Day"]==day) & (df["Period"]==period)]["Teacher_Name"])

def teacher_period_info(df, teacher, day, period):
    rows = df[(df["Teacher_Name"]==teacher) & (df["Day"]==day) & (df["Period"]==period)]
    return (rows.iloc[0]["Class"], rows.iloc[0]["Subject"]) if not rows.empty else ("","")

def master_load(df, teacher, day) -> int:
    return len(df[(df["Teacher_Name"]==teacher) & (df["Day"]==day)])

def append_log(record: dict) -> None:
    log = pd.DataFrame([record])
    if os.path.exists(LOG_CSV):
        log.to_csv(LOG_CSV, mode="a", header=False, index=False)
    else:
        log.to_csv(LOG_CSV, index=False)

def whatsapp_text(report_df: pd.DataFrame, day: str, date_val) -> str:
    lines = [f"📋 *KV BURHANPUR ARRANGEMENT*", f"📅 {day}, {date_val}", ""]
    absent_list = report_df["Absent_Teacher"].unique()
    lines.append(f"🔴 Absent: {', '.join(short_name(t) for t in absent_list)}")
    lines.append("")
    for period in sorted(report_df["Period"].unique()):
        lines.append(f"*Period {period}*")
        for _, r in report_df[report_df["Period"]==period].iterrows():
            if r["Type"] == "CLUBBED":
                club_info = r.get("Sub_Own_Class","")
                if r.get("Sub_Own_Subject"): club_info += f" · {r['Sub_Own_Subject']}"
                club_note = f" _(clubbing with {club_info})_" if club_info else ""
                lines.append(
                    f"  🔀  {r['Class']} ({r['Subject']}) — "
                    f"{short_name(r['Absent_Teacher'])} → *{short_name(r['Substitute'])}*{club_note}"
                )
            else:
                lines.append(
                    f"  ✅  {r['Class']} ({r['Subject']}) — "
                    f"{short_name(r['Absent_Teacher'])} → *{short_name(r['Substitute'])}*"
                )
        lines.append("")
    lines.append("_Generated by KV Burhanpur Arrangement App_")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# PDF Export
# ─────────────────────────────────────────────────────────────────────────────
def generate_arrangement_pdf(report_df: pd.DataFrame, selected_day: str, date_val) -> bytes:
    import io
    from reportlab.lib import colors as C
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.platypus import (
        SimpleDocTemplate, Table, TableStyle,
        Paragraph, Spacer, HRFlowable,
    )

    # ── palette ──────────────────────────────────────────────────────────────
    BLUE   = C.HexColor("#1E40AF")
    BLUE2  = C.HexColor("#DBEAFE")
    STRIPE = C.HexColor("#F8FAFC")
    BORDER = C.HexColor("#CBD5E1")
    RED    = C.HexColor("#DC2626")
    ORANGE = C.HexColor("#D97706")
    DARK   = C.HexColor("#1E293B")
    MID    = C.HexColor("#64748B")
    GREEN  = C.HexColor("#15803D")

    # ── paragraph styles ─────────────────────────────────────────────────────
    def ps(name, font="Helvetica", size=8, align=TA_CENTER, textColor=DARK, **kw):
        return ParagraphStyle(name, fontName=font, fontSize=size,
                              alignment=align, textColor=textColor, **kw)

    sty_school  = ps("school", "Helvetica-Bold", 13, textColor=BLUE, spaceAfter=2)
    sty_title   = ps("title",  "Helvetica-Bold", 10, textColor=DARK, spaceAfter=1)
    sty_meta    = ps("meta",   size=8, textColor=MID, spaceAfter=0)
    sty_hdr     = ps("hdr",    "Helvetica-Bold", 8, textColor=C.white)
    sty_cell_c  = ps("cc",     size=8)
    sty_cell_l  = ps("cl",     size=8, align=TA_LEFT)
    sty_bold_l  = ps("bl",     "Helvetica-Bold", 8, align=TA_LEFT, textColor=DARK)
    sty_unassign= ps("ua",     "Helvetica-Bold", 8, align=TA_LEFT, textColor=RED)
    sty_clubbed = ps("cb",     "Helvetica-Bold", 8, align=TA_LEFT, textColor=ORANGE)
    sty_sig_hdr = ps("sh",     "Helvetica-Bold", 9, textColor=DARK)
    sty_sig_sub = ps("ss",     size=7.5, textColor=MID, spaceBefore=2)

    # ── document ─────────────────────────────────────────────────────────────
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=1.5*cm, rightMargin=1.5*cm,
        topMargin=1.5*cm, bottomMargin=2*cm,
        title=f"Arrangement {date_val}",
    )

    elems = []

    # header
    elems.append(Paragraph("PM SHRI KENDRIYA VIDYALAYA BURHANPUR", sty_school))
    elems.append(Paragraph("DAILY TEACHER ARRANGEMENT", sty_title))
    elems.append(Paragraph(f"{selected_day}  ·  {date_val}  ·  Academic Year 2026-27", sty_meta))
    elems.append(Spacer(1, 0.2*cm))
    elems.append(HRFlowable(width="100%", thickness=1.5, color=BLUE, spaceAfter=0.25*cm))
    elems.append(Spacer(1, 0.15*cm))

    # ── table ────────────────────────────────────────────────────────────────
    # Sort: absent teacher → period
    sdf = report_df.sort_values(["Absent_Teacher", "Period"]).reset_index(drop=True)

    col_w = [0.9*cm, 3.7*cm, 0.9*cm, 2.1*cm, 2.1*cm, 3.7*cm, 1.4*cm, 2.2*cm]
    # total = 17cm  (A4 portrait usable ≈ 18cm)

    col_labels = ["S.No", "Absent Teacher", "Per.", "Class /\nSection",
                  "Subject", "Substitute Teacher", "Mode", "Sign"]
    tbl_data = [[Paragraph(h, sty_hdr) for h in col_labels]]

    for idx, row in sdf.iterrows():
        absent  = short_name(row["Absent_Teacher"])
        sub     = row.get("Substitute", "— Not Assigned —")
        mode    = row.get("Type", "SUBSTITUTE")
        own_cls = row.get("Sub_Own_Class", "")

        if sub == "— Not Assigned —":
            sub_p  = Paragraph("UNASSIGNED ⚠", sty_unassign)
            mode_p = Paragraph("—",            sty_cell_c)
        elif mode == "CLUBBED":
            own_subj = row.get("Sub_Own_Subject", "")
            club_detail = own_cls + (f" · {own_subj}" if own_subj else "")
            sub_text = short_name(sub) + (f"\n(clubbing: {club_detail})" if club_detail else "")
            sub_p  = Paragraph(sub_text, sty_clubbed)
            mode_p = Paragraph("CLUB",   ps("cn","Helvetica-Bold",6.5,textColor=ORANGE))
        else:
            sub_p  = Paragraph(short_name(sub), sty_bold_l)
            mode_p = Paragraph("SUB",           ps("sm",size=7.5,textColor=GREEN))

        tbl_data.append([
            Paragraph(str(idx + 1),                sty_cell_c),
            Paragraph(absent,                      sty_cell_l),
            Paragraph(str(row["Period"]),           sty_cell_c),
            Paragraph(str(row.get("Class", "")),    sty_cell_c),
            Paragraph(str(row.get("Subject", "")),  sty_cell_c),
            sub_p, mode_p,
            Paragraph("", sty_cell_c),   # Sign column (blank)
        ])

    tbl = Table(tbl_data, colWidths=col_w, repeatRows=1)

    ts = TableStyle([
        ("BACKGROUND",   (0,0), (-1,0),  BLUE),
        ("ALIGN",        (0,0), (-1,0),  "CENTER"),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING",   (0,0), (-1,-1), 5),
        ("BOTTOMPADDING",(0,0), (-1,-1), 5),
        ("LEFTPADDING",  (0,0), (-1,-1), 4),
        ("RIGHTPADDING", (0,0), (-1,-1), 4),
        ("GRID",         (0,0), (-1,-1), 0.4, BORDER),
        ("LINEBELOW",    (0,0), (-1,0),  1.5, BLUE),
    ])

    # Zebra stripes
    for i in range(1, len(tbl_data)):
        ts.add("BACKGROUND", (0,i), (-1,i), STRIPE if i % 2 == 0 else C.white)

    # Highlight unassigned rows
    for i, (_, row) in enumerate(sdf.iterrows(), start=1):
        if row.get("Substitute", "") == "— Not Assigned —":
            ts.add("BACKGROUND", (0,i), (-1,i), C.HexColor("#FEF2F2"))

    # Merge absent-teacher cells for consecutive same teacher
    prev_t, grp_s = None, None
    groups: list[tuple[int,int]] = []
    for i, (_, row) in enumerate(sdf.iterrows()):
        ridx = i + 1
        t = row["Absent_Teacher"]
        if t != prev_t:
            if grp_s is not None and ridx - 1 > grp_s:
                groups.append((grp_s, ridx - 1))
            grp_s, prev_t = ridx, t
    if grp_s is not None and len(sdf) > grp_s:
        groups.append((grp_s, len(sdf)))

    for r0, r1 in groups:
        ts.add("SPAN",   (1, r0), (1, r1))
        ts.add("VALIGN", (1, r0), (1, r1), "MIDDLE")
        ts.add("LINEBELOW", (1, r0), (1, r1-1), 0, C.white)  # hide inner borders

    tbl.setStyle(ts)
    elems.append(tbl)

    # ── footer ────────────────────────────────────────────────────────────────
    elems.append(Spacer(1, 0.9*cm))
    elems.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceAfter=0.5*cm))

    sig_data = [
        [Paragraph("", sty_sig_sub),              "",
         Paragraph("", sty_sig_sub)],
        [Paragraph("_" * 35, sty_sig_sub),        "",
         Paragraph("_" * 35, sty_sig_sub)],
        [Paragraph("Time-Table In-Charge", sty_sig_hdr), "",
         Paragraph("PRINCIPAL", sty_sig_hdr)],
        [Paragraph("PM Shri KV Burhanpur", sty_sig_sub), "",
         Paragraph("PM Shri KV Burhanpur", sty_sig_sub)],
    ]
    sig_tbl = Table(sig_data, colWidths=[6.5*cm, 4*cm, 6.5*cm])
    sig_tbl.setStyle(TableStyle([
        ("ALIGN",     (0,0), (-1,-1), "CENTER"),
        ("VALIGN",    (0,0), (-1,-1), "BOTTOM"),
        ("TOPPADDING",(0,0), (-1,-1), 3),
    ]))
    elems.append(sig_tbl)

    doc.build(elems)
    buf.seek(0)
    return buf.getvalue()


# ─────────────────────────────────────────────────────────────────────────────
# Period-dot HTML  (blue=teaching, orange=sub, gray=free)
# ─────────────────────────────────────────────────────────────────────────────
def period_dot(p: int, status: str, cls: str = "") -> str:
    styles = {
        "teaching": ("background:#3B82F6;color:#fff;", "T"),
        "sub":      ("background:#F59E0B;color:#fff;", "S"),
        "free":     ("background:#E2E8F0;color:#94A3B8;", str(p)),
    }
    sty, lbl = styles.get(status, styles["free"])
    tip = f'title="P{p}: {cls}"' if cls else f'title="P{p}"'
    return (
        f'<div {tip} style="width:24px;height:24px;border-radius:6px;{sty}'
        f'font-size:.58rem;font-weight:700;display:inline-flex;align-items:center;'
        f'justify-content:center;flex-shrink:0;">{lbl}</div>'
    )

def period_dots_row(period_status: dict, period_class: dict = None) -> str:
    dots = [period_dot(p, period_status.get(p,"free"),
                       (period_class or {}).get(p,"")) for p in ALL_PERIODS]
    return '<div style="display:flex;gap:.2rem;flex-wrap:wrap;">' + "".join(dots) + "</div>"

def teacher_status_card(td: dict) -> str:
    t      = td["name"]
    color  = av_color(t)
    ini    = av_initials(t)
    sname  = short_name(t)
    free_c = td["free_count"]
    busy_c = 8 - free_c
    load_p = busy_c / 8
    lc     = "#EF4444" if load_p >= 0.75 else "#F59E0B" if load_p >= 0.5 else "#10B981"
    dots   = period_dots_row(td["period_status"], td.get("period_class", {}))

    return f"""
    <div style="background:#fff;border-radius:14px;padding:.9rem;
                box-shadow:0 1px 8px rgba(0,0,0,.05);">
        <div style="display:flex;align-items:center;gap:.6rem;margin-bottom:.5rem;">
            <div style="width:38px;height:38px;border-radius:10px;background:{color};
                        color:#fff;font-size:.8rem;font-weight:700;flex-shrink:0;
                        display:flex;align-items:center;justify-content:center;">{ini}</div>
            <div style="flex:1;min-width:0;">
                <div style="font-size:.82rem;font-weight:700;color:#0F172A;
                            white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">{sname}</div>
                <div style="font-size:.67rem;margin-top:.05rem;">
                    <span style="color:#10B981;font-weight:600;">{free_c} free</span>
                    &nbsp;·&nbsp;<span style="color:#64748B;">{busy_c} busy</span>
                </div>
            </div>
        </div>
        <div style="height:3px;background:#E2E8F0;border-radius:999px;margin-bottom:.45rem;">
            <div style="width:{load_p*100:.0f}%;height:100%;background:{lc};border-radius:999px;"></div>
        </div>
        {dots}
    </div>
    """

# ─────────────────────────────────────────────────────────────────────────────
# Page config & CSS
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="KV Burhanpur · Arrangement",
    page_icon="🏫",
    layout="centered",
    initial_sidebar_state="collapsed",
)

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
html,body,[class*="css"]{ font-family:'Inter',sans-serif !important; }
.stApp{ background:#F1F5F9; }
#MainMenu,footer,header{ visibility:hidden; }
.block-container{ padding:1.2rem .9rem 5rem !important; max-width:780px !important; }

.kv-header{
    background:linear-gradient(135deg,#1E3A8A 0%,#2563EB 60%,#3B82F6 100%);
    border-radius:20px; padding:1.6rem 1.5rem 1.4rem;
    color:#fff; text-align:center; margin-bottom:1rem;
    box-shadow:0 4px 24px rgba(37,99,235,.3);
}
.kv-header h1{ font-size:1.35rem; font-weight:800; margin:0 0 .2rem; letter-spacing:-.4px; }
.kv-header p{ font-size:.75rem; opacity:.75; margin:0; }

.card{ background:#fff; border-radius:16px; padding:1.1rem 1.2rem; margin-bottom:.85rem;
        box-shadow:0 1px 2px rgba(0,0,0,.05),0 2px 12px rgba(0,0,0,.04); }
.card-label{ font-size:.65rem; font-weight:700; letter-spacing:.1em;
             text-transform:uppercase; color:#94A3B8; margin-bottom:.65rem; }

.prog-card{ background:#fff; border-radius:16px; padding:1rem 1.2rem; margin-bottom:.85rem;
             box-shadow:0 1px 2px rgba(0,0,0,.05),0 2px 12px rgba(0,0,0,.04); }
.prog-numbers{ font-size:1.5rem; font-weight:800; color:#1E293B; }
.prog-sub{ font-size:.72rem; color:#64748B; margin-top:.1rem; }

.absent-card{ background:#fff; border-radius:18px; margin-bottom:1rem;
              box-shadow:0 1px 2px rgba(0,0,0,.05),0 4px 20px rgba(0,0,0,.06); overflow:hidden; }
.absent-card-head{ padding:.9rem 1.1rem .8rem; border-bottom:1px solid #F1F5F9;
                   display:flex; align-items:center; gap:.75rem; }
.teacher-av{ width:44px; height:44px; border-radius:12px;
             display:flex; align-items:center; justify-content:center;
             font-size:.95rem; font-weight:800; color:#fff; flex-shrink:0; }
.teacher-name{ font-size:.95rem; font-weight:700; color:#0F172A; }
.teacher-meta{ font-size:.7rem; color:#94A3B8; margin-top:.05rem; }

.period-row{ display:flex; align-items:center; gap:.6rem;
             padding:.6rem 1.1rem; border-bottom:1px solid #F8FAFC; }
.period-row:last-child{ border-bottom:none; }
.period-row:hover{ background:#FAFBFF; }
.pnum{ min-width:30px; height:30px; border-radius:8px; background:#EFF6FF; color:#1D4ED8;
       font-size:.75rem; font-weight:700; display:flex; align-items:center;
       justify-content:center; flex-shrink:0; }
.pnum.club{ background:#FFF7ED; color:#C2410C; }
.pinfo{ flex:1; min-width:0; }
.pclass{ font-size:.82rem; font-weight:600; color:#1E293B; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }

.s-pill{ display:inline-flex; align-items:center; gap:.3rem; border-radius:999px;
         padding:.2rem .6rem; font-size:.68rem; font-weight:600; white-space:nowrap; flex-shrink:0; }
.s-pending{ background:#FEF2F2; color:#B91C1C; border:1px solid #FECACA; }
.s-covered{ background:#F0FDF4; color:#15803D; border:1px solid #BBF7D0; }
.s-clubbed { background:#FFFBEB; color:#92400E; border:1px solid #FDE68A; }
.sub-av{ width:22px; height:22px; border-radius:50%; display:inline-flex; align-items:center;
         justify-content:center; font-size:.55rem; font-weight:700; color:#fff;
         vertical-align:middle; margin-right:.2rem; flex-shrink:0; }

/* stat tiles */
.stat-tile{ background:#fff; border-radius:14px; padding:.9rem 1rem; text-align:center;
             box-shadow:0 1px 8px rgba(0,0,0,.05); }
.stat-num{ font-size:1.6rem; font-weight:800; color:#0F172A; }
.stat-lbl{ font-size:.65rem; color:#94A3B8; text-transform:uppercase; letter-spacing:.06em; }

/* legend dot */
.leg-dot{ display:inline-block; width:12px; height:12px; border-radius:3px;
          margin-right:.3rem; vertical-align:middle; }

div[data-testid="stSelectbox"] > label{ font-size:.72rem !important; color:#64748B !important; }
div[data-testid="stSelectbox"] > div > div{
    border-radius:10px !important; border-color:#E2E8F0 !important;
    font-size:.82rem !important; background:#FAFBFF !important; color:#1E293B !important; }
div[data-testid="stSelectbox"] span,
div[data-testid="stSelectbox"] div[data-baseweb="select"] *{ color:#1E293B !important; }
div[data-testid="stSelectbox"] svg{ fill:#64748B !important; }
div[data-testid="stMultiSelect"] > div > div{
    border-radius:10px !important; border-color:#E2E8F0 !important; font-size:.82rem !important; }
div[data-testid="stDateInput"] input{ border-radius:10px !important; border-color:#E2E8F0 !important; }

div[data-testid="stButton"] > button[kind="primary"]{
    background:linear-gradient(135deg,#1E40AF,#3B82F6) !important;
    border:none !important; border-radius:12px !important; font-weight:700 !important; }
div[data-testid="stButton"] > button[kind="primary"]:hover{
    opacity:.9 !important; box-shadow:0 4px 14px rgba(59,130,246,.4) !important; transform:translateY(-1px); }
div[data-testid="stButton"] > button[kind="secondary"]{
    border-radius:10px !important; border-color:#E2E8F0 !important;
    font-size:.78rem !important; color:#475569 !important; background:#F8FAFC !important; }
div[data-testid="stDownloadButton"] > button{
    background:#F0FDF4 !important; color:#15803D !important;
    border:1.5px solid #86EFAC !important; border-radius:12px !important;
    font-weight:600 !important; width:100% !important; }
div[data-testid="stAlert"]{ border-radius:12px !important; font-size:.8rem !important; }
div[data-testid="stExpander"]{ border-radius:14px !important; border-color:#E2E8F0 !important; overflow:hidden; }
div[data-testid="stDataFrame"]{ border-radius:12px !important; overflow:hidden; }
div[data-testid="stProgressBar"] > div > div{
    background:linear-gradient(90deg,#22C55E,#16A34A) !important; border-radius:999px !important; }
div[data-testid="stTextArea"] textarea{
    border-radius:12px !important; border-color:#E2E8F0 !important;
    font-size:.75rem !important; background:#F8FAFC !important; font-family:'Courier New',monospace !important; }

/* tab strip */
div[data-testid="stTabs"] > div:first-child{ background:#fff; border-radius:14px 14px 0 0;
    box-shadow:0 1px 0 #E2E8F0; padding:.25rem .5rem 0; margin-bottom:0; }
div[data-testid="stTabs"] > div:first-child button{
    font-size:.82rem !important; font-weight:600 !important;
    color:#475569 !important; border-radius:10px 10px 0 0 !important;
    padding:.5rem 1rem !important; }
div[data-testid="stTabs"] > div:first-child button:hover{ color:#1E293B !important; background:#F1F5F9 !important; }
div[data-testid="stTabs"] > div:first-child button[aria-selected="true"]{
    color:#1E40AF !important; border-bottom:2px solid #2563EB !important; background:#EFF6FF !important; }
div[data-testid="stTabs"] > div:first-child button p{
    color:inherit !important; font-size:.82rem !important; font-weight:600 !important; }

@media(max-width:600px){
    .block-container{ padding:.9rem .6rem 4rem !important; }
    .kv-header{ padding:1.2rem 1rem 1rem; border-radius:16px; }
    .kv-header h1{ font-size:1.1rem; }
    .period-row{ padding:.5rem .8rem; gap:.4rem; }
}
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# Guard
# ─────────────────────────────────────────────────────────────────────────────
if not os.path.exists(MASTER_CSV):
    st.error(f"`{MASTER_CSV}` not found. Run `parse_timetable.py` first.")
    st.stop()

df           = load_master()
all_teachers = sorted(df["Teacher_Name"].unique())

# ─────────────────────────────────────────────────────────────────────────────
# Header
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="kv-header">
    <h1>🏫 KV Burhanpur</h1>
    <p>Teacher Arrangement &amp; Substitution · Academic Year 2026-27</p>
</div>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — always visible (above tabs)
# ─────────────────────────────────────────────────────────────────────────────
st.markdown('<div class="card">', unsafe_allow_html=True)
st.markdown('<p class="card-label">Morning Setup</p>', unsafe_allow_html=True)
today_day    = DAY_MAP.get(datetime.date.today().weekday(), "MON")
c1, c2       = st.columns(2)
selected_day = c1.selectbox("Day", DAYS_ORDER, index=DAYS_ORDER.index(today_day))
date_val     = c2.date_input("Date", value=datetime.date.today())
absent_teachers = st.multiselect(
    "Mark Teachers as Absent",
    options=all_teachers,
    placeholder="Search and select absent teachers…",
)
st.markdown("</div>", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# Build period list & init session state (needed by both tabs)
# ─────────────────────────────────────────────────────────────────────────────
absent_periods: list[dict] = []
for t in absent_teachers:
    for _, row in get_schedule(df, t, selected_day).iterrows():
        absent_periods.append({"teacher": t, "period": int(row["Period"]),
                                "cls": row["Class"], "subj": row["Subject"]})
absent_periods.sort(key=lambda x: (x["period"], x["teacher"]))

for e in absent_periods:
    k_sub  = f"sub_{e['teacher']}_{e['period']}"
    k_club = f"club_{e['teacher']}_{e['period']}"
    if k_sub  not in st.session_state: st.session_state[k_sub]  = "— Not Assigned —"
    if k_club not in st.session_state: st.session_state[k_club] = False

# ─────────────────────────────────────────────────────────────────────────────
# Tabs
# ─────────────────────────────────────────────────────────────────────────────
tab_arr, tab_status = st.tabs(["📋  Arrangement", "👥  Teacher Status"])

# ══════════════════════════════════════════════════════════════════════════════
#  TAB 1 — Arrangement
# ══════════════════════════════════════════════════════════════════════════════
with tab_arr:
    if not absent_teachers:
        st.markdown(
            '<div style="text-align:center;padding:3rem 1rem;">'
            '<div style="font-size:2.5rem;margin-bottom:.75rem;">☀️</div>'
            '<div style="font-size:.95rem;font-weight:600;color:#334155;">Good morning!</div>'
            '<div style="font-size:.8rem;color:#94A3B8;margin-top:.3rem;">'
            'Mark absent teachers above to begin the arrangement.</div></div>',
            unsafe_allow_html=True)
        st.stop()

    if not absent_periods:
        st.warning(f"None of the selected teachers have classes on **{selected_day}**.")
        st.stop()

    # ── helpers that read session state ──────────────────────────────────────
    def compute_sub_workload() -> dict[str, int]:
        wl: dict[str, int] = {}
        for e in absent_periods:
            v = st.session_state.get(f"sub_{e['teacher']}_{e['period']}", "— Not Assigned —")
            if v != "— Not Assigned —":
                wl[v] = wl.get(v, 0) + 1
        return wl

    def auto_fill_all():
        sub_wl = compute_sub_workload()
        for e in absent_periods:
            k_sub  = f"sub_{e['teacher']}_{e['period']}"
            k_club = f"club_{e['teacher']}_{e['period']}"
            if st.session_state.get(k_sub, "— Not Assigned —") != "— Not Assigned —":
                continue
            period = e["period"]
            period_busy = busy_set(df, selected_day, period)
            already_this = {
                st.session_state.get(f"sub_{e2['teacher']}_{period}", "— Not Assigned —")
                for e2 in absent_periods
                if e2["period"] == period and e2["teacher"] != e["teacher"]
            } - {"— Not Assigned —"}
            unavail = period_busy | already_this | set(absent_teachers)
            free    = [t for t in all_teachers if t not in unavail]
            if free:
                best = min(free, key=lambda t: master_load(df, t, selected_day) + sub_wl.get(t, 0))
                st.session_state[k_sub]  = best
                st.session_state[k_club] = False
                sub_wl[best] = sub_wl.get(best, 0) + 1

    # ── Progress card ─────────────────────────────────────────────────────────
    total   = len(absent_periods)
    covered = sum(
        1 for e in absent_periods
        if st.session_state.get(f"sub_{e['teacher']}_{e['period']}", "— Not Assigned —") != "— Not Assigned —"
    )
    pct = covered / total if total else 0

    st.markdown('<div class="prog-card">', unsafe_allow_html=True)
    pc1, pc2, pc3 = st.columns([2, 1, 1])
    with pc1:
        st.markdown(
            f'<div class="prog-numbers">{covered}'
            f'<span style="font-size:1rem;font-weight:500;color:#94A3B8;"> / {total}</span></div>'
            f'<div class="prog-sub">Periods covered</div>', unsafe_allow_html=True)
        st.progress(pct)
    with pc2:
        st.markdown(
            f'<div style="font-size:1.2rem;font-weight:800;color:#EF4444;">{total - covered}</div>'
            f'<div class="prog-sub">Pending</div>', unsafe_allow_html=True)
    with pc3:
        st.markdown(
            f'<div style="font-size:1.2rem;font-weight:800;color:#10B981;">{len(absent_teachers)}</div>'
            f'<div class="prog-sub">Absent</div>', unsafe_allow_html=True)
    st.markdown("</div>", unsafe_allow_html=True)

    # ── Auto-fill button ──────────────────────────────────────────────────────
    _, af_col = st.columns([3, 1])
    with af_col:
        if st.button("⚡ Auto-Fill All", use_container_width=True):
            auto_fill_all()
            st.rerun()

    # ── Per-teacher cards ─────────────────────────────────────────────────────
    for teacher in absent_teachers:
        t_periods = [e for e in absent_periods if e["teacher"] == teacher]
        if not t_periods:
            continue

        color  = av_color(teacher)
        ini    = av_initials(teacher)
        sname  = short_name(teacher)
        t_cov  = sum(1 for e in t_periods
                     if st.session_state.get(f"sub_{teacher}_{e['period']}", "— Not Assigned —") != "— Not Assigned —")

        st.markdown(f"""
        <div class="absent-card">
            <div class="absent-card-head">
                <div class="teacher-av" style="background:{color};">{ini}</div>
                <div>
                    <div class="teacher-name">{sname}</div>
                    <div class="teacher-meta">{len(t_periods)} periods today
                    &nbsp;·&nbsp; {t_cov}/{len(t_periods)} assigned</div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        for e in t_periods:
            period       = e["period"]
            cls          = e["cls"]
            subj         = e["subj"]
            k_sub        = f"sub_{teacher}_{period}"
            k_club       = f"club_{teacher}_{period}"
            current_sub  = st.session_state.get(k_sub,  "— Not Assigned —")
            club_mode    = st.session_state.get(k_club, False)
            is_assigned  = current_sub != "— Not Assigned —"

            period_busy  = busy_set(df, selected_day, period)
            already_this = {
                st.session_state.get(f"sub_{e2['teacher']}_{period}", "— Not Assigned —")
                for e2 in absent_periods
                if e2["period"] == period and e2["teacher"] != teacher
            } - {"— Not Assigned —"}
            unavail        = period_busy | already_this | set(absent_teachers)
            free_teachers  = [t for t in all_teachers if t not in unavail]
            # Club = any teacher occupied this period (master timetable OR already a sub)
            occupied_this  = period_busy | already_this
            club_teachers  = [t for t in all_teachers
                              if t in occupied_this and t not in set(absent_teachers)]

            def _club_label(t: str) -> str:
                """Show what this teacher is doing during this period."""
                if t in period_busy:
                    cls_info = teacher_period_info(df, t, selected_day, period)[0]
                    return f"{short_name(t)}  ⚠ teaching {cls_info}"
                # They're a substitute for another absent teacher this period
                for e2 in absent_periods:
                    if e2["period"] == period and e2["teacher"] != teacher:
                        if st.session_state.get(f"sub_{e2['teacher']}_{period}") == t:
                            return f"{short_name(t)}  🔀 subbing {e2['cls']}"
                return short_name(t)

            if not is_assigned:
                status_html = '<span class="s-pill s-pending">● Unassigned</span>'
            elif club_mode:
                tc, _ = teacher_period_info(df, current_sub, selected_day, period)
                status_html = f'<span class="s-pill s-clubbed">🔀 Clubbed · {tc}</span>'
            else:
                c  = av_color(current_sub)
                i  = av_initials(current_sub)
                sn = short_name(current_sub)
                status_html = (
                    f'<span class="s-pill s-covered">'
                    f'<span class="sub-av" style="background:{c};">{i}</span>{sn}</span>'
                )

            pnum_cls = "pnum club" if club_mode else "pnum"
            subj_str = f" · {subj}" if subj else ""

            st.markdown(f"""
            <div class="period-row">
                <div class="{pnum_cls}">P{period}</div>
                <div class="pinfo"><div class="pclass">{cls}{subj_str}</div></div>
                {status_html}
            </div>
            """, unsafe_allow_html=True)

            sub_wl = compute_sub_workload()
            if not club_mode:
                opts = ["— Not Assigned —"] + sorted(
                    free_teachers,
                    key=lambda t: master_load(df, t, selected_day) + sub_wl.get(t, 0),
                )
                disp = [o if o == "— Not Assigned —"
                        else f"{short_name(o)}  [{master_load(df,o,selected_day)+sub_wl.get(o,0)} periods today]"
                        for o in opts]
                sel_idx = opts.index(current_sub) if current_sub in opts else 0
                col_sel, col_club = st.columns([3, 1])
                with col_sel:
                    chosen_d = st.selectbox(
                        f"sub_{teacher}_{period}_sel",
                        options=disp, index=sel_idx,
                        key=f"disp_{teacher}_{period}",
                        label_visibility="collapsed",
                    )
                    chosen = opts[disp.index(chosen_d)]
                    if chosen != current_sub:
                        st.session_state[k_sub] = chosen
                        st.rerun()
                with col_club:
                    if st.button("🔀 Club", key=f"clubbtn_{teacher}_{period}", use_container_width=True):
                        st.session_state[k_club] = True
                        st.session_state[k_sub]  = "— Not Assigned —"
                        st.rerun()
            else:
                c_opts = ["— Not Assigned —"] + sorted(club_teachers)
                c_disp = [o if o == "— Not Assigned —" else _club_label(o)
                          for o in c_opts]
                sel_idx_c = c_opts.index(current_sub) if current_sub in c_opts else 0
                col_csel, col_back = st.columns([3, 1])
                with col_csel:
                    chosen_cd = st.selectbox(
                        f"club_{teacher}_{period}_sel",
                        options=c_disp, index=sel_idx_c,
                        key=f"clubdisp_{teacher}_{period}",
                        label_visibility="collapsed",
                    )
                    chosen_c = c_opts[c_disp.index(chosen_cd)]
                    if chosen_c != current_sub:
                        st.session_state[k_sub] = chosen_c
                        st.rerun()
                with col_back:
                    if st.button("↩ Back", key=f"backbtn_{teacher}_{period}", use_container_width=True):
                        st.session_state[k_club] = False
                        st.session_state[k_sub]  = "— Not Assigned —"
                        st.rerun()

        st.markdown("</div>", unsafe_allow_html=True)

    # ── Generate report ───────────────────────────────────────────────────────
    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("📋 Finalise & Generate Report", type="primary", use_container_width=True):
        missing = [
            f"P{e['period']} ({short_name(e['teacher'])})"
            for e in absent_periods
            if st.session_state.get(f"sub_{e['teacher']}_{e['period']}", "— Not Assigned —") == "— Not Assigned —"
        ]
        if missing:
            st.warning(f"Still unassigned: {', '.join(missing)}")
        else:
            rows = []
            for e in absent_periods:
                sub  = st.session_state[f"sub_{e['teacher']}_{e['period']}"]
                club = st.session_state[f"club_{e['teacher']}_{e['period']}"]
                tc, ts = teacher_period_info(df, sub, selected_day, e["period"]) if club else ("","")
                rows.append({"Date": str(date_val), "Day": selected_day,
                             "Period": e["period"], "Absent_Teacher": e["teacher"],
                             "Class": e["cls"], "Subject": e["subj"],
                             "Substitute": sub, "Type": "CLUBBED" if club else "SUBSTITUTE",
                             "Sub_Own_Class": tc, "Sub_Own_Subject": ts})
            report_df = pd.DataFrame(rows)
            for rec in rows:
                append_log(rec)

            st.markdown('<div class="card">', unsafe_allow_html=True)
            st.markdown(f'<p class="card-label">Arrangement Sheet · {selected_day} {date_val}</p>',
                        unsafe_allow_html=True)
            # Build display-friendly dataframe
            disp_df = report_df[["Period","Absent_Teacher","Class","Subject","Substitute","Type","Sub_Own_Class","Sub_Own_Subject"]].copy()
            disp_df["Substitute Teacher"] = disp_df.apply(
                lambda r: (
                    f"{short_name(r['Substitute'])}  🔀 (clubbing with {r['Sub_Own_Class']}"
                    + (f" · {r['Sub_Own_Subject']}" if r['Sub_Own_Subject'] else "")
                    + ")"
                ) if r["Type"] == "CLUBBED" and r["Sub_Own_Class"]
                else short_name(r["Substitute"]),
                axis=1,
            )
            disp_df["Mode"] = disp_df["Type"]
            st.dataframe(
                disp_df[["Period","Absent_Teacher","Class","Subject","Substitute Teacher","Mode"]].rename(
                    columns={"Absent_Teacher": "Absent Teacher"}),
                use_container_width=True, hide_index=True)
            wa = whatsapp_text(report_df, selected_day, date_val)
            st.text_area("📱 WhatsApp-Ready Summary", wa, height=220)
            absent_slug = "_".join(short_name(t).replace(" ","") for t in absent_teachers)

            # Generate PDF
            pdf_bytes = generate_arrangement_pdf(report_df, selected_day, date_val)

            dl1, dl2, dl3 = st.columns(3)
            with dl1:
                st.download_button(
                    "📄 Download PDF",
                    data=pdf_bytes,
                    file_name=f"arrangement_{absent_slug}_{date_val}.pdf",
                    mime="application/pdf",
                )
            with dl2:
                st.download_button(
                    "⬇ Download CSV",
                    data=report_df.to_csv(index=False).encode(),
                    file_name=f"arrangement_{absent_slug}_{date_val}.csv",
                    mime="text/csv",
                )
            with dl3:
                st.download_button(
                    "📱 Download Text",
                    data=wa.encode(),
                    file_name=f"arrangement_{absent_slug}_{date_val}.txt",
                    mime="text/plain",
                )
            st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    with st.expander("📂 Past Arrangements Log"):
        if os.path.exists(LOG_CSV):
            st.dataframe(pd.read_csv(LOG_CSV), use_container_width=True, hide_index=True)
        else:
            st.caption("No arrangements saved yet.")

# ══════════════════════════════════════════════════════════════════════════════
#  TAB 2 — Teacher Status Dashboard
# ══════════════════════════════════════════════════════════════════════════════
with tab_status:
    present_teachers = [t for t in all_teachers if t not in absent_teachers]

    # ── Compute per-teacher status for selected day ───────────────────────────
    teacher_data: list[dict] = []
    for t in present_teachers:
        master_ps: set[int] = set(
            df[(df["Teacher_Name"]==t) & (df["Day"]==selected_day)]["Period"].astype(int)
        )
        # Periods where this teacher has been assigned as substitute today
        sub_ps: set[int] = set()
        sub_for: dict[int, str] = {}     # period → absent teacher name
        for e in absent_periods:
            k = f"sub_{e['teacher']}_{e['period']}"
            if st.session_state.get(k, "— Not Assigned —") == t:
                sub_ps.add(e["period"])
                sub_for[e["period"]] = e["teacher"]

        period_status: dict[int, str] = {}
        period_class:  dict[int, str] = {}
        for p in ALL_PERIODS:
            if p in master_ps:
                period_status[p] = "teaching"
                rows = df[(df["Teacher_Name"]==t) & (df["Day"]==selected_day) & (df["Period"]==p)]
                period_class[p]  = rows.iloc[0]["Class"] if not rows.empty else ""
            elif p in sub_ps:
                period_status[p] = "sub"
                period_class[p]  = f"Sub for {short_name(sub_for[p])}"
            else:
                period_status[p] = "free"
                period_class[p]  = ""

        free_count = sum(1 for s in period_status.values() if s == "free")
        teacher_data.append({
            "name": t, "period_status": period_status, "period_class": period_class,
            "master_count": len(master_ps), "sub_count": len(sub_ps),
            "free_count": free_count,
        })

    # Sort: most free periods first
    teacher_data.sort(key=lambda x: (-x["free_count"], x["name"]))

    # ── Summary stat tiles ────────────────────────────────────────────────────
    n_present  = len(present_teachers)
    n_absent   = len(absent_teachers)
    n_free_all = sum(1 for td in teacher_data if td["free_count"] == 8)
    n_on_sub   = sum(1 for td in teacher_data if td["sub_count"] > 0)

    metrics = [
        (n_present,  "Present",    "#10B981", "In school today"),
        (n_absent,   "Absent",     "#EF4444", "Called in / on leave"),
        (n_free_all, "Fully Free", "#3B82F6", "No classes assigned"),
        (n_on_sub,   "On Sub",     "#F59E0B", "Covering absent classes"),
    ]

    tiles_html = "".join(
        f'<div style="background:#fff;border-radius:14px;padding:.9rem .75rem;'
        f'text-align:center;box-shadow:0 1px 8px rgba(0,0,0,.05);">'
        f'<div style="font-size:1.6rem;font-weight:800;color:{col};line-height:1;">{val}</div>'
        f'<div style="font-size:.68rem;font-weight:700;letter-spacing:.07em;'
        f'text-transform:uppercase;color:#94A3B8;margin:.25rem 0 .2rem;">{lbl}</div>'
        f'<div style="font-size:.65rem;color:#CBD5E1;line-height:1.3;">{desc}</div>'
        f'</div>'
        for val, lbl, col, desc in metrics
    )
    st.markdown(
        f'<div style="display:grid;grid-template-columns:repeat(4,1fr);'
        f'gap:.6rem;margin-bottom:.9rem;">{tiles_html}</div>',
        unsafe_allow_html=True,
    )

    # ── Legend ────────────────────────────────────────────────────────────────
    st.markdown(
        '<div style="display:flex;gap:1rem;margin-bottom:.8rem;flex-wrap:wrap;">'
        '<span><span class="leg-dot" style="background:#3B82F6;"></span>'
        '<span style="font-size:.72rem;color:#475569;font-weight:500;">Teaching</span></span>'
        '<span><span class="leg-dot" style="background:#F59E0B;"></span>'
        '<span style="font-size:.72rem;color:#475569;font-weight:500;">Substituting</span></span>'
        '<span><span class="leg-dot" style="background:#E2E8F0;"></span>'
        '<span style="font-size:.72rem;color:#475569;font-weight:500;">Free</span></span>'
        '</div>',
        unsafe_allow_html=True)

    # ── Absent teachers (collapsed) ───────────────────────────────────────────
    if absent_teachers:
        pills = "".join(
            f'<span style="display:inline-block;background:#FEF2F2;color:#B91C1C;'
            f'border:1px solid #FECACA;border-radius:999px;padding:.15rem .55rem;'
            f'font-size:.68rem;font-weight:600;margin:.1rem;">{short_name(t)}</span>'
            for t in absent_teachers
        )
        st.markdown(
            f'<div style="background:#FEF2F2;border:1px solid #FECACA;border-radius:12px;'
            f'padding:.6rem .85rem;margin-bottom:.85rem;font-size:.72rem;color:#B91C1C;">'
            f'🔴 <strong>Absent today:</strong> {pills}</div>',
            unsafe_allow_html=True)

    # ── Teacher grid (2 columns) ──────────────────────────────────────────────
    if not teacher_data:
        st.info("All teachers are marked absent.")
    else:
        for i in range(0, len(teacher_data), 2):
            cols = st.columns(2, gap="small")
            for j, td in enumerate(teacher_data[i:i+2]):
                with cols[j]:
                    st.markdown(teacher_status_card(td), unsafe_allow_html=True)
                    # Period detail on hover via expander
                    with st.expander("Details", expanded=False):
                        rows_detail = []
                        for p in ALL_PERIODS:
                            s  = td["period_status"][p]
                            cl = td["period_class"][p]
                            rows_detail.append({
                                "Period": p,
                                "Status": s.title(),
                                "Class / Note": cl,
                            })
                        st.dataframe(pd.DataFrame(rows_detail),
                                     use_container_width=True, hide_index=True)
                    st.markdown("<br>", unsafe_allow_html=True)
